#+TITLE:     Org-page: Static Site Generator
#+AUTHOR:    Kevin Hu, Erich L Foster
#+EMAIL:     erichlf@gmail.com
#+DATE:      2020-09-27

*** This is a re-write, in python, of the original org-page develop by [[https:://github.com/sillykelvin][sillykelvin]].

  The point of the re-write is to allow someone to write org files, but not
  require emacs. This allows one to, for example, use github actions to publish
  your org files.

* Introduction

  Org-page is a static site generator based on [[http://orgmode.org/][org-mode]].

  Org-page provides the following features:

  1) Org sources and html files managed by git
  2) Incremental publication (according to =git diff= command)
  3) Category support
  4) Tags support (auto generated)
  5) RSS support (auto generated)
  6) Search engine support (auto generated)
  7) A beautiful theme
  8) Theme customization support
  9) Commenting (implemented using disqus/duoshuo/hashover)
  10) Website traffic analytics (implemented using google analytics)
  11) Index/about page support (auto generated if no default is provided)
  12) Highly customizable

  *[[erichlf.github.io][Here]] is my personal site generated by org-page. You
  can take a look at my html files and org source files
  [[https:://github.com/erichlf/erichlf.github.io][here]]. If you want to give
  org-page a try, you could take them as an example. Or you can look at the
  original developers [[sillykelvin.github.io][site]] and there
  [[https:://github.com/sillykelvin/sillykelvin.github.io][source]]*

** Workflow

   The workflow has been greatly simplified from the previous workflow. It only
   requires you to run a python script and then you can do as you please.

  *org-page is designed to handle all of these kinds of changes but since
  deletion does not happen often, org-page has not implemented it yet*

* Usage

** Installation

  Simply clone the repo.

** Configuration

   Add the following lines to your =.emacs= file:

** Publication

  It is up to you how to publish your content. However, I would recommend using
  a github action.

* Dependencies

  1. orgparse
  2. pystache

* Known issues

  - Currently the deletion change handler has not been implemented so
    if you deleted some org sources, you will have to manually delete
    corresponding generated html files.
  - URI path change detection is not available. That is, if you make a
    post with the URI "/blog/2013/03/25/the-old-post-name" and then
    change this value in your org source, org-page would be unable to
    detect that this has happened. it will only publish a new html
    file for you so you need to delete the old html file related to
    the old URI manually.
